do not vote on own weights
fetchai/colearn pull request #185
Opened 2021-12-08 12:04 UTC by n-hutton

2021-12-08 12:05 UTC, n-hutton commented on colearn/ml_interface.py
> +    vote: Optional[bool]
None indicates own vote/invalid

2021-12-10 13:49 UTC, evsmithx requested changes
I think the gRPC interface will be broken by this because it has vote: bool. Can you modify that as well?

2021-12-10 13:49 UTC, evsmithx commented on colearn/standalone_driver.py
> +            learner.mli_accept_weights(prop_weights_list[0].weights)
Minor, but this code would be equivalent and clearer if `new_weights` replaced `prop_weights_list[0].weights`. Also if you're not using the loop index then you can get rid of enumerate().

2021-12-10 13:49 UTC, evsmithx commented on colearn/utils/plot.py
> +        grey_patch_handle = mpatches.Patch(color=grey_colour / 256, label='N/A vote')
"Did not vote" would be a better label.

2021-12-15 07:35 UTC, n-hutton commented on colearn_grpc/grpc_learner_server.py
> +            if proposed_weights.vote is not None:
grpc allows you to not specify values

2021-12-15 11:22 UTC, evsmithx approved these changes

2021-12-15 11:22 UTC, evsmithx commented on colearn/standalone_driver.py
> +            learner.mli_accept_weights(prop_weights_list[0].weights)
You marked the conversation as resolved but you haven't fixed it!

2021-12-15 17:05 UTC, evsmithx approved these changes

2021-12-15 17:05 UTC, merged